// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// H.264 帧类型（与 `openh264` 及 scrcpy 帧标志语义一致）。
enum H264FrameType {
  /// 关键帧（IDR / Idr，可独立解码）。
  idr,

  /// 非关键帧（P 帧）。
  nonIdr,

  /// 未知 / 未标记。
  unknown,
}
