// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'codec.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 会话方向（对应 3.7 / 3.8 / 3.9）。
enum SessionDirection {
  /// Win/Lin 控制 Android（scrcpy + ADB）。
  scrcpy,

  /// Windows → Windows 本机自控制。
  desktopSelf,

  /// Linux → Windows（Linux 控制 Windows）。
  desktopFrom,
}

/// 会话生命周期状态。
enum SessionState {
  stopped,
  running,

  /// 因缺少能力（codec/捕获/输入）而优雅结束。
  ended,
}

/// 会话产出的 H.264 帧（编码端 / 解码端通用）。
class VideoFrame {
  final int width;
  final int height;
  final H264FrameType frameType;

  /// AnnexB 压缩流（编码端）或 RGBA8（解码端），由 `is_decoded` 区分。
  final Uint8List data;

  /// `true` 表示是解码后的 RGBA8，`false` 表示 AnnexB 压缩流。
  final bool isDecoded;

  const VideoFrame({
    required this.width,
    required this.height,
    required this.frameType,
    required this.data,
    required this.isDecoded,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      frameType.hashCode ^
      data.hashCode ^
      isDecoded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          frameType == other.frameType &&
          data == other.data &&
          isDecoded == other.isDecoded;
}
