// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../protocol/message.dart';
import '../protocol/types.dart';
import '../transport.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectionHandle>>
                abstract class ConnectionHandle implements RustOpaqueInterface {
                    /// 当前生效的传输层（未连接时为 None）。
 Future<ActiveTransport?>  activeTransport({required String id });


/// 建立到设备的连接：优先 QUIC，失败回退 TCP。
 Future<ConnectionState>  connect({required DeviceInfo dev });


/// 断开指定设备连接。
 Future<void>  disconnect({required String id });


  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
/// 创建一个连接管理器（惰性启动 tokio 运行时）。
static Future<ConnectionHandle>  newInstance()=>RustLib.instance.api.crateApiConnectionConnectionHandleNew();


/// 向指定连接发送一帧控制消息（静默丢弃接收到的业务帧，由上层按需消费）。
 Future<void>  send({required String id , required MessageType msgType , required List<int> payload });


/// 查询指定设备连接状态。
 Future<ConnectionState>  state({required String id });



                    
                }
                
            