// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../protocol/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `into_local`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`


            

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DiscoveryHandle>>
                abstract class DiscoveryHandle implements RustOpaqueInterface {
                    static Future<DiscoveryHandle>  default_()=>RustLib.instance.api.crateApiDiscoveryDiscoveryHandleDefault();


/// 当前已发现的设备列表（按名称排序）。
 Future<List<DeviceInfo>>  listDevices();


  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
/// 创建一个空句柄（未开始广播/浏览）。
static Future<DiscoveryHandle>  newInstance()=>RustLib.instance.api.crateApiDiscoveryDiscoveryHandleNew();


/// 启动 mDNS 广播（让本机可被其他设备发现）。
 Future<void>  startBroadcast({required BroadcastConfig cfg , required String hostIp });


/// 启动 mDNS 浏览（发现局域网内其他设备，填充共享缓存）。
 Future<void>  startBrowse();


/// 当前发现状态。
 Future<DiscoveryState>  state();


/// 停止 mDNS 广播。
 Future<void>  stopBroadcast();


/// 停止 mDNS 浏览。
 Future<void>  stopBrowse();



                    
                }
                

/// 设备广播参数（由 Dart 侧 `DiscoveryService` 传入）。
class BroadcastConfig  {
                /// 设备唯一 ID（UUID v4）。
final String id;
/// 显示名（如 “Edgerd-Desktop”）。
final String name;
/// 系统类型。
final DeviceSystem system;
/// QUIC 监听端口。
final int quicPort;
/// TCP 监听端口。
final int tcpPort;
/// 首选传输层。
final Transport preferredTransport;
/// 协议版本，如 "1.0.0"。
final String protocolVersion;

                const BroadcastConfig({required this.id ,required this.name ,required this.system ,required this.quicPort ,required this.tcpPort ,required this.preferredTransport ,required this.protocolVersion ,});





        @override
        int get hashCode => id.hashCode^name.hashCode^system.hashCode^quicPort.hashCode^tcpPort.hashCode^preferredTransport.hashCode^protocolVersion.hashCode;



        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is BroadcastConfig &&
                runtimeType == other.runtimeType
                && id == other.id&& name == other.name&& system == other.system&& quicPort == other.quicPort&& tcpPort == other.tcpPort&& preferredTransport == other.preferredTransport&& protocolVersion == other.protocolVersion;

            }
            