// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../codec.dart';
import '../frb_generated.dart';
import '../session.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SessionHandle>>
abstract class SessionHandle implements RustOpaqueInterface {
  /// 当前 target 是否具备软编解码后端（降级探测）。
  Future<bool> codecAvailable();

  /// 依方向创建会话（分辨率宽高偶数对齐）。
  Future<void> create({
    required String id,
    required SessionDirection direction,
    required int width,
    required int height,
  });

  static Future<SessionHandle> default_() =>
      RustLib.instance.api.crateApiSessionSessionHandleDefault();

  /// 下发按键（keycode 用 Android/Linux EV 码）。
  Future<void> inputKey({
    required String id,
    required int keycode,
    required bool down,
  });

  /// 下发滚动。
  Future<void> inputScroll({
    required String id,
    required int x,
    required int y,
    required double hscroll,
    required double vscroll,
  });

  /// 下发触摸（`action`: 0=Down, 1=Move, 2=Up）。
  Future<void> inputTouch({
    required String id,
    required int x,
    required int y,
    required int action,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 创建会话管理器。
  static Future<SessionHandle> newInstance() =>
      RustLib.instance.api.crateApiSessionSessionHandleNew();

  /// 拉取一帧解码画面（RGBA8）；无则 `None`。
  Future<VideoFrame?> nextFrame({required String id});

  /// 当前可用的输入注入后端名（探测降级；无则 `"null"`）。
  Future<String> probeInputBackend();

  /// 启动会话。
  Future<void> start({required String id});

  /// 查询会话状态（无该会话返回 `None`）。
  Future<SessionState?> state({required String id});

  /// 停止会话。
  Future<void> stop({required String id});
}
