// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 返回一条问候语，证明 Dart 能同步拿到 Rust 的返回值。
///
/// 修改此处返回值并重新运行 `flutter_rust_bridge_codegen generate`，
/// Flutter 侧 `greet` 的返回将同步变化。
Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);
