// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            

            /// 连接状态。
enum ConnectionState {
                    disconnected,
connecting,
connected,
reconnecting,
error,
                    ;
                    
                }

/// 一台被发现的设备实例。
class DeviceInfo  {
                /// 设备唯一 ID，UUID v4，首次启动生成并持久化。
final String id;
/// 显示名（如 “Edgerd-Desktop”）。
final String name;
/// 系统类型：win / linux / android。
final DeviceSystem system;
/// 局域网 IP（IPv4 字符串）。
final String ip;
/// QUIC 监听端口（动态分配）。
final int quicPort;
/// TCP 监听端口（动态分配）。
final int tcpPort;
/// 支持的传输层列表，如 ["quic","tcp"]。
final List<Transport> supportedTransports;
/// 登录状态：false=离线，true=在线。
final bool online;
/// 优先使用的传输层（QUIC 默认）。
final Transport preferredTransport;
/// 协议版本，如 "1.0.0"。
final String protocolVersion;

                const DeviceInfo({required this.id ,required this.name ,required this.system ,required this.ip ,required this.quicPort ,required this.tcpPort ,required this.supportedTransports ,required this.online ,required this.preferredTransport ,required this.protocolVersion ,});





        @override
        int get hashCode => id.hashCode^name.hashCode^system.hashCode^ip.hashCode^quicPort.hashCode^tcpPort.hashCode^supportedTransports.hashCode^online.hashCode^preferredTransport.hashCode^protocolVersion.hashCode;



        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is DeviceInfo &&
                runtimeType == other.runtimeType
                && id == other.id&& name == other.name&& system == other.system&& ip == other.ip&& quicPort == other.quicPort&& tcpPort == other.tcpPort&& supportedTransports == other.supportedTransports&& online == other.online&& preferredTransport == other.preferredTransport&& protocolVersion == other.protocolVersion;

            }

/// 设备系统类型。为便于跨语言序列化，直接以小写字符串落盘。
enum DeviceSystem {
                    windows,
linux,
android,
unknown,
                    ;
                    
                }

/// 设备发现状态。
enum DiscoveryState {
                    stopped,
starting,
running,
error,
                    ;
                    
                }

/// 传输层选择。`preferred_transport` 决定默认优先使用的链路。
enum Transport {
                    quic,
tcp,
                    ;
                    
                }
            